config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  namespace :api do
    namespace :v1 do
      resources :fruits
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fruit.rb
class Fruit < ApplicationRecord
end

app/controllers/api/v1/fruits_controller.rb
class Api::V1::FruitsController < ApplicationController
  before_action :set_fruit, only: %i[ show edit update destroy ]

  # GET /fruits or /fruits.json
  def index
    @fruits = Fruit.all
    render json: @fruits
  end

  # GET /fruits/1 or /fruits/1.json
  def show
  end

  # GET /fruits/new
  def new
    @fruit = Fruit.new
  end

  # GET /fruits/1/edit
  def edit
  end

  # POST /fruits or /fruits.json
  def create
    @fruit = Fruit.new(fruit_params)
    # render json: @fruits
    respond_to do |format|
      if @fruit.save
        # format.html { redirect_to @fruit, notice: "Fruit was successfully created." }
        # format.json { render :show, status: :created, location: @fruits }
        format.json { render json: @fruits }
      else
        # format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fruits/1 or /fruits/1.json
  def update
    respond_to do |format|
      if @fruit.update(fruit_params)
        format.json { render @fruits }
      else
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fruits/1 or /fruits/1.json
  def destroy
    @fruit.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fruit
      @fruit = Fruit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fruit_params
      params.require(:fruit).permit(:id, :name, :desc)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/fruits/_form.html.erb
<%= form_with(model: fruit) do |form| %>
  <% if fruit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fruit.errors.count, "error") %> prohibited this fruit from being saved:</h2>

      <ul>
        <% fruit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fruits/edit.html.erb
<h1>Editing Fruit</h1>

<%= render 'form', fruit: @fruit %>

<%= link_to 'Show', @fruit %> |
<%= link_to 'Back', fruits_path %>

app/views/fruits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fruits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fruits.each do |fruit| %>
      <tr>
        <td><%= fruit.name %></td>
        <td><%= fruit.desc %></td>
        <td><%= link_to 'Show', fruit %></td>
        <td><%= link_to 'Edit', edit_fruit_path(fruit) %></td>
        <td><%= link_to 'Destroy', fruit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fruit', new_fruit_path %>

app/views/fruits/new.html.erb
<h1>New Fruit</h1>

<%= render 'form', fruit: @fruit %>

<%= link_to 'Back', fruits_path %>

app/views/fruits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fruit.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @fruit.desc %>
</p>

<%= link_to 'Edit', edit_fruit_path(@fruit) %> |
<%= link_to 'Back', fruits_path %>

app/views/home/index.html.erb
<%= react_component 'Main' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleReact</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="ui inverted menu">
    <div class="ui container">
      <a href="#" class="header item">
        Project Name
      </a>
      <a href="#" class="item">Home</a>
      <div class="ui simple dropdown item">
        Dropdown <i class="dropdown icon"></i>
        <div class="menu">
          <a class="item" href="#">Link Item</a>
          <a class="item" href="#">Link Item</a>
          <div class="divider"></div>
          <div class="header">Header Item</div>
          <div class="item">
            <i class="dropdown icon"></i>
            Sub Menu
            <div class="menu">
              <a class="item" href="#">Link Item</a>
              <a class="item" href="#">Link Item</a>
            </div>
          </div>
          <a class="item" href="#">Link Item</a>
        </div>
      </div>
    </div>
  </div>
  <div class="ui main text container">
    <%= yield %>
  </div>
  </body>
</html>